### ISSUE TITLE
bug: 익명유저가 profile에 들어가는 것을 방지 

### ISSUE THREAD

**Issue by ChoiWheatley** [ESTsoft-Book-Project/bookstore#16]
## 버그 발생법

1. 웹 브라우저 쿠키를 지워 로그아웃 상태로 만든다.
2. `localhost:8000/users/profile`로 들어간다
3. **수정하기** 또는 **계정 삭제하기** 버튼을 누른다.

## 아래는 에러 본문입니다.

```python
Internal Server Error: /users/profile/
Traceback (most recent call last):
  File "/home/chltm/workspace/bookstore/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/chltm/workspace/bookstore/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chltm/workspace/bookstore/users/views.py", line 46, in profile
    user.save()
  File "/home/chltm/workspace/bookstore/venv/lib/python3.11/site-packages/django/contrib/auth/models.py", line 443, in save
    raise NotImplementedError(
NotImplementedError: Django doesn't provide a DB representation for AnonymousUser.
```

---

ref: 47a76c2787bd9a128b7dfe9f009fcf2749749994

**Comment by ChoiWheatley** [comment]
[제가 연습했던 유튜브 영상](https://youtu.be/sMqDJovFO-Y?t=7364)을 참고하시면 `LoginRequiredMixin`과 `UserPassesTestMixin` 믹스인을 상속받아 해당 기능을 사용하는 모습을 볼 수 있습니다.

**Comment by allen9535** [comment]
해당 사항에 대해 두 가지 해결책을 찾았습니다.
첫번째는 django.contrib.auth.decorators에서 login_required 데코레이터를 사용하는 것입니다. 로그인한 유저가 아니면 profile에 들어가는 것을 방지할 수 있고, 필요한 경우 다른 url에 리다이렉트할 수 있습니다. 아래는 예시입니다.
```python
@login_required(login_url="/users/signin/")
def profile(request):
    if request.method == "POST":
        user = request.user
        user.nickname = request.POST["nickname"]
        user.email = request.POST["email"]
        update_password = request.POST["password"]
        if update_password:
            user.set_password(update_password)
            update_session_auth_hash(request, user)
        user.save()
        return JsonResponse({"message": "회원 정보 수정이 완료되었습니다."})
    else:
        return render(request, "profile.html", {"user": request.user})
```
두번째는 django.contrib.auth의 is_authenticated 또는 is_anonymous 변수를 사용하는 것입니다. Django의 인증 기능을 사용해 로그인한 사용자라면 is_authenticated는 True 값을 가지게 됩니다. is_anonymous는 is_authenticated의 반대 값을 가지게 되어 있습니다. 사실 login_required 데코레이터에서도 is_authenticated를 사용하기 때문에 작동 원리는 비슷하다고 생각합니다.
```python
def profile(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            user = request.user
            user.nickname = request.POST["nickname"]
            user.email = request.POST["email"]
            update_password = request.POST["password"]
            if update_password:
                user.set_password(update_password)
                update_session_auth_hash(request, user)
            user.save()
            return JsonResponse({"message": "회원 정보 수정이 완료되었습니다."})
        else:
            return render(request, "profile.html", {"user": request.user})
    else:
        return redirect(reverse("users:signin"))
```
